/**/fake_localization:
  ros__parameters:
    # The launch file always overrides this parameter with the `use_sim_time`
    # launch argument. This value is kept only to make this YAML file complete
    # when it is inspected outside the launch context.
    use_sim_time: false
    global_frame: map
    odometry_frame: robot_odom
    base_frame: robot_base_link
    delta_x: 0.0
    delta_y: 0.0
    delta_yaw: 0.0
    # Time tolerance added to the TF timestamp.
    transform_tolerance: 0.1
